controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index